// Assessment tips mapped by tool ID - provides quick clinical guidance on each calculator card
export const assessmentTips: Record<string, string> = {
  // Neurological
  gcs: 'Assess on arrival and with any neurological change',
  nihss: 'Score within 20 min of arrival for thrombolytic eligibility',
  lams: 'Use prehospital for LVO stroke screening',
  slams: 'Quick stroke severity triage in the field',
  ich: 'Predict 30-day mortality in intracerebral hemorrhage',
  hunthess: 'Grade on admission for SAH prognosis',
  race: 'Prehospital large vessel occlusion detection',
  mrs: 'Assess functional disability at discharge or follow-up',
  abcd2: 'Stratify stroke risk after TIA within 48 hours',
  fisher: 'Grade SAH severity on initial CT scan',
  menza: 'Screen cognitive function; repeat with clinical change',
  '2helps2b': 'Estimate seizure risk on continuous EEG monitoring',
  setnet: 'Emergency triage tool for acute stroke',
  tis: 'Evaluate trunk control in stroke rehab patients',
  fast: 'Rapid stroke screen — any positive sign warrants 911',
  befast: 'Extended stroke screen catching posterior circulation events',

  // Psychiatric
  phq9: 'Screen for depression; reassess every 2 weeks during treatment',
  gad7: 'Screen for anxiety; monitor treatment response',
  cam: 'Assess delirium with acute mental status changes',
  '4at': 'Rapid delirium screen at bedside; takes <2 minutes',
  ciwa: 'Monitor alcohol withdrawal every 1-2 hours in acute phase',
  cssrs: 'Use for any patient with suicidal ideation or attempt',
  moca: 'Screen mild cognitive impairment; more sensitive than MMSE',
  smast: 'Brief alcoholism screening in clinical settings',
  smastg: 'Alcoholism screening adapted for geriatric patients',

  // Cardiovascular
  heart: 'Use for undifferentiated chest pain in the ED',
  timi: 'Risk-stratify ACS for treatment decisions',
  chads: 'Assess annually in atrial fibrillation patients',
  hasbled: 'Evaluate bleeding risk before starting anticoagulation',
  wells: 'Estimate DVT/PE probability before imaging',
  '4peps': 'Four-level PE probability assessment',
  killip: 'Classify heart failure severity post-MI',
  nyha: 'Classify heart failure symptoms for treatment planning',
  rcri: 'Preoperative cardiac risk for non-cardiac surgery',
  framingham: 'Estimate 10-year cardiovascular disease risk',
  duke: 'Apply modified Duke criteria for endocarditis diagnosis',
  grace: 'Predict in-hospital and 6-month ACS mortality',
  map: 'Calculate MAP; target ≥65 mmHg in sepsis',
  ascvd: 'Guide statin therapy decisions (2013 ACC/AHA)',
  qtc: 'Check before and during QT-prolonging medications',
  prevent: 'AHA 2023 updated CVD risk equations',
  guptamica: 'Perioperative MI/cardiac arrest risk estimation',
  dasi: 'Estimate functional capacity without exercise testing',
  perc: 'Rule out PE without D-dimer in low-risk patients',
  ldl: 'Calculate LDL when triglycerides <400 mg/dL',
  sgarbossa: 'Diagnose MI in the presence of LBBB or paced rhythm',
  sexshock: 'Predict cardiogenic shock risk in ACS patients',
  shanghai: 'Risk stratification for Brugada syndrome',
  dilqts: 'Assess drug-induced long QT syndrome risk',
  simonbroome: 'Criteria for familial hypercholesterolemia diagnosis',
  preop: 'Combined preoperative cardiac risk summary',

  // Respiratory
  curb65: 'Determine pneumonia admission vs. outpatient treatment',
  aagradient: 'Evaluate oxygenation; distinguish V/Q causes',
  bode: 'Predict COPD mortality and guide management',
  mmrc: 'Quantify dyspnea severity in COPD patients',
  psiport: 'Risk-stratify community-acquired pneumonia',
  ariscat: 'Predict postoperative pulmonary complications',
  stopbang: 'Screen for obstructive sleep apnea preoperatively',
  abg: 'Interpret acid-base status and oxygenation',
  mallampati: 'Assess airway difficulty before intubation',
  asa: 'Classify physical status for anesthesia planning',

  // Sepsis & Infection
  qsofa: 'Bedside screen for sepsis outside ICU',
  sirs: 'Identify systemic inflammatory response',
  sofa: 'Quantify organ dysfunction in ICU; track daily',
  centor: 'Guide antibiotic decisions for sore throat',
  '4c': 'Predict in-hospital mortality in COVID-19',
  sepsiseset: 'Sepsis screening and early treatment checklist',
  shapiro: 'Decide necessity of blood cultures in ED',
  shorr: 'Estimate MRSA risk in pneumonia patients',

  // Critical Care
  apache: 'Calculate within 24 hours of ICU admission',
  saps2: 'ICU mortality prediction within first 24 hours',
  saps3: 'ICU mortality prediction at admission (within 1 hour)',
  cprmetronome: 'Maintain 100-120 compressions/min during CPR',
  aclsnarrator: 'Real-time ACLS algorithm guidance with auto-documentation',
  shockindex: 'HR/SBP >0.9 suggests occult shock',
  scorten: 'Predict mortality in TEN/SJS within 24 hours',

  // Trauma
  trauma: 'Calculate RTS, ISS, and TRISS for trauma severity',

  // Hematology
  blood: 'Verify blood type compatibility before transfusion',
  padua: 'Assess VTE risk in hospitalized medical patients',
  caprini: 'VTE risk assessment for surgical patients',
  '4ts': 'Evaluate probability of heparin-induced thrombocytopenia',
  sicklecell: 'Calculate RBC exchange volume for sickle cell crisis',

  // Pediatric
  apgar: 'Score at 1 and 5 minutes after birth',
  pedsgcs: 'Use age-appropriate scale for children <2 years',
  pews: 'Escalate care with score ≥3; reassess hourly if elevated',
  pedsdose: 'Weight-based dosing; always double-check calculations',
  palsnarrator: 'Step-by-step PALS algorithm during pediatric codes',
  pedsresustape: 'Length-based dosing for pediatric emergencies',
  edd: 'Calculate estimated due date from LMP or ultrasound',
  pecarn: 'Guide CT decision in pediatric minor head injury',
  maintenance: 'Calculate maintenance IV fluids using 4-2-1 rule',
  finnegan: 'Score neonatal withdrawal every 3-4 hours',
  aappeds: 'AAP guidelines for pediatric hypertension staging',
  sipa: 'Age-adjusted shock index for pediatric trauma',

  // Renal
  ckdepi: 'Preferred GFR equation; use 2021 race-free formula',
  akikdigo: 'Stage AKI using KDIGO creatinine/urine criteria',
  cockcroftgault: 'Use for drug dosing adjustments in renal impairment',
  mdrd: 'Legacy GFR; CKD-EPI 2021 preferred for new patients',
  calciumcorrection: 'Correct calcium when albumin is abnormal',
  aniongap: 'Evaluate metabolic acidosis etiology',
  osmolality: 'Calculate osmolar gap for toxic alcohol ingestion',
  fena: 'Distinguish prerenal from intrinsic renal failure',
  freewaterdeficit: 'Guide free water replacement in hypernatremia',
  nacorrection: 'Correct sodium for hyperglycemia (1.6 mEq per 100 mg/dL)',
  urinaryprotein: 'Quantify proteinuria from spot urine sample',
  urineanion: 'Help differentiate causes of metabolic acidosis',

  // Oncology
  ecog: 'Assess performance status before treatment decisions',
  karnofsky: 'Quantify functional status; guide treatment eligibility',
  g8: 'Geriatric screening before oncology treatment',
  esas: 'Patient self-report symptom burden assessment',
  pap: 'Estimate survival in advanced cancer patients',
  pps: 'Track functional decline in palliative care',
  uiss: 'Stage renal cell carcinoma for treatment planning',
  capra: 'Predict prostate cancer recurrence after prostatectomy',

  // General
  bmi: 'Screen nutritional status; calculate BSA for dosing',
  ibw: 'Use IBW/ABW for ventilator settings and drug dosing',
  fib4: 'Non-invasive liver fibrosis screening',
  homair: 'Assess insulin resistance in metabolic syndrome',
  meldna: 'Prioritize liver transplant candidates',
  childpugh: 'Classify cirrhosis severity for prognosis',
  steroid: 'Convert between glucocorticoid equivalencies',
  mme: 'Calculate opioid equivalencies for safe prescribing',
  '6mwd': 'Assess functional exercise capacity',
  ukeld: 'UK liver transplant prioritization score',
  meldpeld: 'Liver transplant priority for adults and pediatrics',
  uceis: 'Endoscopic severity index for ulcerative colitis',
  truelovewitts: 'Classify UC severity for treatment decisions',
  bisap: 'Predict pancreatitis severity within 24 hours',
  ranson: 'Assess pancreatitis prognosis at 0 and 48 hours',
  glasgowimrie: 'Score pancreatitis severity within 48 hours',
  uas: 'Track urticaria activity over 7 days',
  aih: 'Simplified scoring for autoimmune hepatitis diagnosis',
  sdai: 'Assess rheumatoid arthritis disease activity',
  mfis: 'Quantify fatigue impact in chronic conditions',

  // Nursing Assessments
  braden: 'Reassess every shift or with condition change',
  morse: 'Reassess on admission, transfer, and status change',
  news2: 'Score every 4-6 hours; escalate with score ≥5',
  rass: 'Target sedation goal; assess before each dose',
  cows: 'Monitor opioid withdrawal to guide treatment',
  flacc: 'Use for preverbal or nonverbal pediatric pain',
  ivdrip: 'Verify drip rate with pump settings',
  aldrete: 'Score ≥9 required for PACU discharge',
  cpot: 'Assess pain in intubated/nonverbal ICU patients',
  painad: 'Pain assessment for patients with advanced dementia',
  wongbaker: 'Self-report faces scale for ages 3+',
  camicu: 'Screen for ICU delirium every shift',
  must: 'Screen malnutrition risk on admission',
  intakeoutput: 'Track fluid balance every shift',
  urineoutput: 'Monitor hourly in critical care; target ≥0.5 mL/kg/hr',
  trueurineoutput: 'Calculate true UO during continuous bladder irrigation',
  tubefeeding: 'Calculate enteral nutrition rates and goals',
  carbcounter: 'Count carbohydrates for insulin dosing',
  nrs: 'Standard numeric pain scale 0-10',
  vas: 'Visual analog pain scale for research precision',
  eat10: 'Screen dysphagia risk; score ≥3 is abnormal',
  guss: 'Bedside swallowing screen before oral intake',
  yaleswallow: 'Validated nurse-administered swallow screen',
  waterswallow: '3-oz water test for aspiration risk',
  torbsst: 'Nurse-led swallowing screen for stroke patients',
  masa: 'Comprehensive swallowing ability assessment',
  fois: 'Track oral intake progression in dysphagia rehab',
  pas: 'Grade penetration/aspiration severity on VFSS/FEES',
  iddsi: 'International diet texture framework reference',

  // Obstetrics & Gynecology
  gestationalage: 'Calculate GA from LMP; confirm with early ultrasound',
  efw: 'Estimate fetal weight using Hadlock formula',
  ovulation: 'Track fertility window for conception planning',
  contraction: 'Time contractions; call provider at 5-1-1 pattern',
  kickcounter: 'Count 10 movements in 2 hours; report decreased movement',
  bishop: 'Assess cervical readiness before labor induction',
  bpp: 'Evaluate fetal wellbeing with 5-component scoring',
  preeclampsia: 'Identify patients needing aspirin prophylaxis',
  gbs: 'Determine intrapartum antibiotic prophylaxis need',
  vbac: 'Estimate TOLAC success probability',
  pph: 'Assess hemorrhage risk factors before delivery',
};
