
-- Update Heparin with comprehensive data
UPDATE public.medications SET
  dosing_info = '{"standard": "Initial bolus 60-80 units/kg (max 5000 units), then 12-18 units/kg/hr infusion", "vte_treatment": "80 units/kg bolus, then 18 units/kg/hr", "acs_treatment": "60 units/kg bolus (max 4000 units), then 12 units/kg/hr", "prophylaxis": "5000 units SubQ q8-12h", "weight_based": true}'::jsonb,
  administration_info = '{"iv_push": {"dilution": "May give undiluted for bolus", "rate": "Over 1-2 minutes", "flush": "NS before and after"}, "iv_infusion": {"concentration": "25,000 units in 500 mL (50 units/mL) or 25,000 units in 250 mL (100 units/mL)", "rate": "Per protocol based on aPTT", "line": "Dedicated line preferred"}, "subq": {"sites": "Abdomen, avoid 2 inches around umbilicus", "technique": "Do not aspirate, do not massage"}}'::jsonb,
  safety_info = '{"black_box_warnings": ["Risk of spinal/epidural hematomas with neuraxial anesthesia"], "contraindications": ["Active major bleeding", "Severe thrombocytopenia", "HIT history", "Uncontrolled hypertension"], "warnings": ["HIT can occur - monitor platelets", "Osteoporosis with long-term use", "Hyperkalemia risk"]}'::jsonb,
  monitoring = '{"parameters": ["aPTT q6h until stable then daily", "Platelets baseline and q2-3 days", "Signs of bleeding", "Hemoglobin/hematocrit"], "therapeutic_range": "aPTT 1.5-2.5x control (60-80 seconds)", "frequency": "aPTT 6 hours after dose change"}'::jsonb,
  hold_parameters = '{"hold_if": ["aPTT > 100 seconds", "Active bleeding", "Platelet count < 50,000", "Planned invasive procedure"], "notify_provider": ["aPTT supratherapeutic", "Signs of bleeding", "Platelet drop > 50%"]}'::jsonb,
  clinical_pearls = ARRAY['Protamine reverses heparin: 1 mg per 100 units given in last 2-3 hours', 'HIT typically occurs 5-10 days after starting - stop immediately if suspected', 'Use anti-Xa levels in obesity, renal failure, or heparin resistance', 'Avoid IM injections while on heparin', 'Document all injection sites for SubQ administration']::text[],
  nursing_guide = '{"iv": {"appropriateness": "Standard for acute anticoagulation", "special_preparation": "Use premixed bags when available, dedicated line", "administration": "Continuous infusion via pump, bolus over 1-2 min", "post_administration": "Monitor aPTT per protocol, assess for bleeding", "patient_teaching": "Report any unusual bleeding or bruising"}, "subq": {"appropriateness": "Prophylaxis dosing", "administration": "Rotate sites, do not rub", "patient_teaching": "Proper injection technique if self-administering"}}'::jsonb,
  pharmacokinetics = '{"absorption": "Not absorbed orally, immediate IV", "distribution": "Does not cross placenta", "metabolism": "Hepatic via heparinase", "elimination": "Renal", "half_life": "60-90 minutes, dose-dependent"}'::jsonb,
  adverse_reactions = '{"common": ["Bleeding", "Injection site hematoma", "Thrombocytopenia"], "serious": ["HIT", "Major hemorrhage", "Osteoporosis (long-term)", "Hyperkalemia", "Skin necrosis"], "frequency": "Bleeding 1-5%, HIT 1-3%"}'::jsonb,
  drug_interactions_info = '{"major": ["Other anticoagulants - additive bleeding risk", "Thrombolytics - severe bleeding risk", "NSAIDs/aspirin - increased bleeding"], "moderate": ["SSRIs - bleeding risk", "Cephalosporins - may enhance effect"], "monitoring": "Coagulation studies with interacting drugs"}'::jsonb,
  high_alert = true,
  double_check_required = true
WHERE LOWER(generic_name) = 'heparin';

-- Update Enoxaparin with comprehensive data
UPDATE public.medications SET
  dosing_info = '{"vte_treatment": "1 mg/kg SubQ q12h or 1.5 mg/kg SubQ daily", "acs_treatment": "1 mg/kg SubQ q12h with aspirin", "prophylaxis": "40 mg SubQ daily or 30 mg SubQ q12h", "renal_adjustment": "CrCl < 30: 1 mg/kg daily for treatment, 30 mg daily for prophylaxis", "obesity": "Consider actual body weight up to 144 kg"}'::jsonb,
  administration_info = '{"subq": {"sites": "Alternating left and right anterolateral abdominal wall", "technique": "Do not expel air bubble, insert full needle length, do not rub", "prefilled_syringe": "Use entire contents, do not expel air bubble before injection"}, "iv_push": {"indication": "STEMI only with thrombolytics", "dose": "30 mg IV bolus"}}'::jsonb,
  safety_info = '{"black_box_warnings": ["Spinal/epidural hematomas with neuraxial anesthesia - can cause paralysis"], "contraindications": ["Active major bleeding", "History of HIT with enoxaparin", "Hypersensitivity to heparin products"], "warnings": ["Use with caution in renal impairment", "Not for IM use", "Contains benzyl alcohol - avoid in neonates"]}'::jsonb,
  monitoring = '{"parameters": ["Anti-Xa levels if monitoring needed", "CBC with platelets", "Serum creatinine", "Signs of bleeding", "Neurological status with epidural"], "frequency": "Platelets periodically, anti-Xa 4 hours post-dose if needed"}'::jsonb,
  hold_parameters = '{"hold_if": ["Active bleeding", "Platelet count < 50,000", "Planned procedure - hold 12-24h prior"], "notify_provider": ["Renal function decline", "Signs of bleeding", "Platelet drop > 50%"]}'::jsonb,
  clinical_pearls = ARRAY['Do NOT expel the air bubble from prefilled syringe - ensures full dose', 'Anti-Xa monitoring useful in obesity, renal impairment, pregnancy', 'Not fully reversed by protamine (60% reversal)', 'Rotate injection sites to prevent lipodystrophy', 'Hold 12-24 hours before procedures depending on dose']::text[],
  nursing_guide = '{"subq": {"appropriateness": "Standard route for LMWH", "special_preparation": "Use prefilled syringe, do not expel air", "administration": "Pinch skin fold, insert at 90 degrees, inject slowly", "post_administration": "Apply gentle pressure, do not rub, document site", "patient_teaching": "Self-injection technique, signs of bleeding to report"}}'::jsonb,
  pharmacokinetics = '{"absorption": "92% bioavailability SubQ", "distribution": "Volume 4.3 L", "metabolism": "Hepatic desulfation and depolymerization", "elimination": "Renal 40% as active fragments", "half_life": "4.5-7 hours"}'::jsonb,
  adverse_reactions = '{"common": ["Injection site bruising", "Bleeding", "Anemia", "Thrombocytopenia"], "serious": ["Major hemorrhage", "HIT", "Spinal hematoma", "Skin necrosis"], "frequency": "Minor bleeding 3-5%"}'::jsonb,
  drug_interactions_info = '{"major": ["Anticoagulants - additive bleeding", "Thrombolytics - severe bleeding risk"], "moderate": ["NSAIDs - increased bleeding", "SSRIs - bleeding risk", "Antiplatelet agents - bleeding risk"], "note": "Routine coagulation monitoring not required"}'::jsonb,
  high_alert = true,
  double_check_required = true
WHERE LOWER(generic_name) = 'enoxaparin';

-- Update Warfarin with comprehensive data
UPDATE public.medications SET
  dosing_info = '{"initial": "2.5-5 mg PO daily, adjust based on INR", "maintenance": "Typically 2-10 mg daily, highly variable", "target_inr": {"afib": "2.0-3.0", "mechanical_valve": "2.5-3.5", "vte": "2.0-3.0"}, "genetic_dosing": "Consider CYP2C9 and VKORC1 polymorphisms"}'::jsonb,
  administration_info = '{"po": {"timing": "Same time daily, preferably evening", "food": "Consistent vitamin K intake important", "missed_dose": "Take as soon as remembered same day, do not double"}, "iv": {"indication": "When oral not possible", "administration": "Slow IV push over 1-2 minutes"}}'::jsonb,
  safety_info = '{"black_box_warnings": ["Major or fatal bleeding risk", "Regular INR monitoring required"], "contraindications": ["Pregnancy (teratogenic)", "Active bleeding", "Recent CNS surgery", "Uncontrolled hypertension"], "warnings": ["Many drug and food interactions", "Requires reliable patient compliance", "Skin necrosis risk especially with protein C/S deficiency"]}'::jsonb,
  monitoring = '{"parameters": ["INR daily until stable then weekly then monthly", "Signs of bleeding", "Hemoglobin periodically"], "therapeutic_range": "INR per indication (usually 2-3)", "frequency": "INR q1-4 weeks when stable"}'::jsonb,
  hold_parameters = '{"hold_if": ["INR > 4.0 - contact provider", "Active bleeding", "Planned surgery"], "reversal": {"minor_bleeding": "Hold dose, vitamin K 2.5-5 mg PO", "major_bleeding": "4-factor PCC + vitamin K 10 mg IV", "life_threatening": "4-factor PCC + vitamin K 10 mg IV + FFP if needed"}}'::jsonb,
  clinical_pearls = ARRAY['Full anticoagulant effect takes 5-7 days - bridge with heparin initially', 'Vitamin K intake should be consistent, not eliminated', 'INR elevated: many causes including diet change, illness, new medications', 'Purple toe syndrome indicates cholesterol emboli', 'Genetic testing can guide initial dosing']::text[],
  nursing_guide = '{"po": {"appropriateness": "Standard for long-term anticoagulation", "administration": "Consistent timing daily", "post_administration": "Monitor for bleeding, educate on interactions", "patient_teaching": "INR monitoring importance, dietary consistency, drug interactions, bleeding signs"}}'::jsonb,
  pharmacokinetics = '{"absorption": "Well absorbed orally", "distribution": "99% protein bound", "metabolism": "Hepatic CYP2C9 (major), CYP3A4, CYP1A2", "elimination": "Renal as metabolites", "half_life": "20-60 hours (mean 40 hours)"}'::jsonb,
  adverse_reactions = '{"common": ["Bleeding", "Bruising"], "serious": ["Major hemorrhage", "Skin necrosis", "Purple toe syndrome", "Calciphylaxis"], "teratogenicity": "Contraindicated in pregnancy - warfarin embryopathy"}'::jsonb,
  drug_interactions_info = '{"major": ["Numerous CYP interactions", "Vitamin K - antagonizes effect", "NSAIDs - bleeding risk", "Azole antifungals - increased INR", "Rifampin - decreased INR", "Amiodarone - increased INR"], "food": ["Vitamin K rich foods affect INR", "Cranberry juice may increase INR", "Alcohol - variable effect"], "monitoring": "INR with any medication change"}'::jsonb,
  high_alert = true,
  double_check_required = true
WHERE LOWER(generic_name) = 'warfarin';

-- Update Apixaban with comprehensive data
UPDATE public.medications SET
  dosing_info = '{"afib": "5 mg PO BID; reduce to 2.5 mg BID if 2 of: age ≥80, weight ≤60 kg, Cr ≥1.5", "vte_treatment": "10 mg BID x 7 days, then 5 mg BID", "vte_prophylaxis": "2.5 mg BID after hip/knee replacement", "secondary_prevention": "2.5 mg BID after 6+ months treatment"}'::jsonb,
  administration_info = '{"po": {"timing": "With or without food, approximately 12 hours apart", "crushing": "May crush and mix with water, apple juice, or applesauce", "ng_tube": "Crushed tablets can be given via NG tube", "missed_dose": "Take as soon as remembered, resume BID schedule"}}'::jsonb,
  safety_info = '{"black_box_warnings": ["Premature discontinuation increases stroke risk in AFib", "Spinal hematoma risk with neuraxial anesthesia"], "contraindications": ["Active pathological bleeding", "Severe hypersensitivity"], "warnings": ["No reliable reversal agent widely available", "Use caution in hepatic impairment", "Not recommended with prosthetic heart valves"]}'::jsonb,
  monitoring = '{"parameters": ["Signs of bleeding", "Renal function periodically", "Hemoglobin if bleeding suspected"], "note": "Routine coagulation monitoring not required", "anti_xa": "Apixaban-specific anti-Xa if level needed"}'::jsonb,
  hold_parameters = '{"hold_if": ["Active bleeding", "Planned procedure - hold 24-48h prior based on bleeding risk", "CrCl < 15 or on dialysis (limited data)"], "reversal": "Andexanet alfa for life-threatening bleeding"}'::jsonb,
  clinical_pearls = ARRAY['Preferred DOAC in renal impairment - least renal elimination', 'No dose adjustment for mild-moderate renal impairment alone', 'Can crush tablets for NG tube administration', 'Dual pathway inhibition reduces VTE with lower bleeding than warfarin', 'Hold at least 48 hours before high bleeding risk procedures']::text[],
  nursing_guide = '{"po": {"appropriateness": "Oral anticoagulant without monitoring requirement", "administration": "BID dosing approximately 12 hours apart", "post_administration": "Assess for bleeding, ensure medication compliance", "patient_teaching": "Importance of not missing doses, no INR monitoring needed, bleeding precautions"}}'::jsonb,
  pharmacokinetics = '{"absorption": "50% bioavailability, food does not affect", "distribution": "87% protein bound", "metabolism": "CYP3A4/5, minimal renal excretion (27%)", "elimination": "Fecal (primary) and renal", "half_life": "12 hours"}'::jsonb,
  adverse_reactions = '{"common": ["Bleeding", "Bruising", "Anemia"], "serious": ["Major hemorrhage", "Spinal hematoma", "Hypersensitivity"], "frequency": "Major bleeding 1-2% annually"}'::jsonb,
  drug_interactions_info = '{"major": ["Strong CYP3A4 and P-gp inhibitors (ketoconazole, ritonavir) - reduce dose", "Strong CYP3A4 and P-gp inducers (rifampin, carbamazepine) - avoid"], "moderate": ["Antiplatelet agents - bleeding risk", "NSAIDs - bleeding risk"], "note": "Fewer interactions than warfarin"}'::jsonb,
  high_alert = true,
  double_check_required = true
WHERE LOWER(generic_name) = 'apixaban';

-- Update Rivaroxaban with comprehensive data
UPDATE public.medications SET
  dosing_info = '{"afib": "20 mg PO daily with evening meal; 15 mg daily if CrCl 15-50", "vte_treatment": "15 mg BID x 21 days, then 20 mg daily with food", "vte_prophylaxis_hip": "10 mg daily x 35 days", "vte_prophylaxis_knee": "10 mg daily x 12 days", "cad_pad": "2.5 mg BID with aspirin"}'::jsonb,
  administration_info = '{"po": {"timing": "With food for doses ≥15 mg to ensure absorption", "crushing": "May crush and mix with applesauce, follow with food", "ng_tube": "May give via NG in stomach, follow with enteral feeding", "missed_dose": "15 mg BID: take immediately if remembered; 20 mg daily: take with next meal"}}'::jsonb,
  safety_info = '{"black_box_warnings": ["Premature discontinuation increases stroke risk", "Spinal hematoma risk with neuraxial anesthesia"], "contraindications": ["Active pathological bleeding", "Severe hypersensitivity"], "warnings": ["Take with food for 15-20 mg doses", "Renal dose adjustment required", "Avoid with strong CYP3A4 and P-gp inhibitors"]}'::jsonb,
  monitoring = '{"parameters": ["Signs of bleeding", "Renal function periodically", "Hemoglobin if bleeding suspected"], "note": "Routine coagulation monitoring not required", "anti_xa": "Rivaroxaban-specific anti-Xa if level needed"}'::jsonb,
  hold_parameters = '{"hold_if": ["Active bleeding", "CrCl < 15", "Planned procedure - hold 24h+ prior based on risk"], "reversal": "Andexanet alfa for life-threatening bleeding; 4-factor PCC may help"}'::jsonb,
  clinical_pearls = ARRAY['MUST take 15-20 mg doses with food - 30-40% absorption decrease without food', 'Once daily dosing may improve compliance', 'More renal elimination than apixaban (36%)', 'Consider apixaban if CrCl < 25', 'VTE treatment requires loading phase (15 mg BID x 21 days)']::text[],
  nursing_guide = '{"po": {"appropriateness": "Oral anticoagulant with food requirement for higher doses", "special_preparation": "Ensure food available for administration", "administration": "Take with food for 15-20 mg doses", "post_administration": "Assess for bleeding, verify taken with food", "patient_teaching": "Critical to take with food, bleeding signs, adherence importance"}}'::jsonb,
  pharmacokinetics = '{"absorption": "80-100% with food, 66% without food", "distribution": "92-95% protein bound", "metabolism": "CYP3A4, CYP2J2", "elimination": "Renal 36% unchanged, fecal", "half_life": "5-9 hours; 11-13 hours in elderly"}'::jsonb,
  adverse_reactions = '{"common": ["Bleeding", "Bruising"], "serious": ["Major hemorrhage", "Spinal hematoma", "Hypersensitivity", "Stevens-Johnson syndrome (rare)"], "frequency": "Major bleeding 2-4% annually"}'::jsonb,
  drug_interactions_info = '{"major": ["Strong CYP3A4 and P-gp inhibitors - avoid or use caution", "Strong CYP3A4 inducers (rifampin) - avoid"], "moderate": ["Antiplatelet agents - bleeding", "NSAIDs - bleeding", "Moderate CYP3A4 inhibitors - use caution in renal impairment"], "note": "Fewer interactions than warfarin"}'::jsonb,
  high_alert = true,
  double_check_required = true
WHERE LOWER(generic_name) = 'rivaroxaban';
